{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e2d54f9-67e6-4c5b-adb3-cf13f7ce3423",
   "metadata": {},
   "outputs": [],
   "source": [
    "library(janitor)\n",
    "library(tidyverse)\n",
    "library(lubridate)\n",
    "library(zoo)\n",
    "library(ggplot2)\n",
    "\n",
    "\n",
    "\n",
    "#oppgave 1\n",
    "\n",
    "lower <- \n",
    "  read_table(\"https://www.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt\") %>% \n",
    "  .[1:which(.$Year %in% \"Year\")-1, ] %>% \n",
    "  clean_names() %>% \n",
    "  .[ , 1:3] %>%  \n",
    "  mutate(dato = ymd(paste(.$year, .$mo, 1, sep = \"-\"))) %>% \n",
    "  mutate_if(is.character, ~as.numeric(.)) %>% \n",
    "  select(dato, globe) %>% \n",
    "  mutate(glidende_snitt = rollmean(globe, 13, fill = NA, align = \"center\"))\n",
    "\n",
    "lower %>% \n",
    "  ggplot(aes(x=dato, y=globe)) + geom_line(col=\"blue\") + theme_bw() +\n",
    "  geom_point(shape=1, col=\"blue\") +\n",
    "  geom_line(aes(y=glidende_snitt), col=\"red\", lwd=1.2) + \n",
    "  labs(x = \"Latest Global Average Tropospheric Tempratures\", \n",
    "       y = \"T Depature from 91-20 Avg. (deg.C)\") + \n",
    "  theme(axis.text.x = element_text(angle = 90, hjust = 1))\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "#Oppgave 2\n",
    "\n",
    "scrape_bake <- function(url, location) {\n",
    "  return(read_table(url) %>% \n",
    "           .[1:which(.$Year %in% \"Year\")-1, ] %>% \n",
    "           clean_names() %>% \n",
    "           mutate(dato = ymd(paste(.$year, .$mo, 1, sep = \"-\"))) %>% \n",
    "           mutate_if(is.character, ~as.numeric(.)) %>% \n",
    "           mutate(nivå = paste0(location)))\n",
    "}\n",
    "url_list <- list(\"http://vortex.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt\",\n",
    "                 \"http://vortex.nsstc.uah.edu/data/msu/v6.0/tmt/uahncdc_mt_6.0.txt\",\n",
    "                 \"http://vortex.nsstc.uah.edu/data/msu/v6.0/ttp/uahncdc_tp_6.0.txt\",\n",
    "                 \"http://vortex.nsstc.uah.edu/data/msu/v6.0/tls/uahncdc_ls_6.0.txt\")\n",
    "location_list <- list(\"Lower Troposphere\",\"Mid-Troposphere\", \"Tropopause\", \"Lower Stratosphere\")\n",
    "\n",
    "d.frame <- map2(url_list, location_list, scrape_bake)\n",
    "d.frame <- ldply(d.frame, data.frame)\n",
    "d.frame <- d.frame %>%  \n",
    "  select(dato, no_pol, nivå) %>% \n",
    "  as_tibble() %>% \n",
    "  mutate(gj.snitt.alle = mean(no_pol))\n",
    "\n",
    "ggplot(d.frame, aes(x = dato, y = no_pol, color = nivå)) + geom_line(linetype = \"dashed\") + \n",
    "  theme_bw() + geom_point(shape = 1)\n",
    "\n",
    "\n",
    "df %>%\n",
    "  ggplot(aes(x=deaths_per_100k, y=fully_vaccinated_pct_of_pop)) +\n",
    "  geom_point(shape=21, fill=\"Blue\", size=2, label=name) + geom_text(hjust=0, vjust=0)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.1.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
